// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppColors: typeof import('./src/components/AppColors.vue')['default']
    AppGenerate: typeof import('./src/components/AppGenerate.vue')['default']
    AppPicker: typeof import('./src/components/AppPicker.vue')['default']
    AppTransition: typeof import('./src/components/AppTransition.vue')['default']
    DarkMode: typeof import('./src/components/DarkMode.vue')['default']
    PickerGrid: typeof import('./src/components/PickerGrid.vue')['default']
    PickerInput: typeof import('./src/components/PickerInput.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}

export { }
